version: '3.8'

services:
  propostas:
    image: propostas-yepag:latest
    networks:
      - theusmnet
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.propostas.rule=Host(`propostas.yepag.com`)"
        - "traefik.http.routers.propostas.entrypoints=websecure"
        - "traefik.http.routers.propostas.tls=true"
        - "traefik.http.routers.propostas.tls.certresolver=letsencrypt"
        - "traefik.http.services.propostas.loadbalancer.server.port=80"
        - "traefik.http.routers.propostas-http.rule=Host(`propostas.yepag.com`)"
        - "traefik.http.routers.propostas-http.entrypoints=web"
        - "traefik.http.routers.propostas-http.middlewares=https-redirect"
        - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
        - "traefik.http.middlewares.https-redirect.redirectscheme.permanent=true"
      replicas: 1
      restart_policy:
        condition: any

networks:
  theusmnet:
    external: true
